#image: gradle:jdk11
#
#stages:
#  - BUILD
#  - TEST
#
#before_script:
#  - export GRADLE_USER_HOME='pwd'/.gradle
#  - chmod +x ./gradlew
#
#cache:
#  key: ${CI_COMMIT_REF_SLUG}
#  paths:
#    - .gradle/wrapper
#    - .gradle/caches
#
#BUILD_JOB:
#  stage: BUILD
#  script:
##    - ./gradlew --build-cache assemble
#    - ./gradlew build
#  artifacts:
#    paths:
#      - ./build/libs/
#
#BUILD_DOCKER:
#  stage: Build
#
#tests:
#  stage: TEST
#  script:
#    - ./gradlew check
#
