image: gradle:jdk11

before_script:
  - export GRADLE_USER_HOME='pwd'/cache/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

package:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew check

