image: gradle:jdk11

stages:
  - build
  - test
#  - deploy

before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/wrapper
    - .gradle/caches

package:
  stage: build
  script:
    - chmod +x ./gradlew
    #    git update-index --chmod=+x also is solution
    - ./gradlew --build-cache assemble

tests:
  stage: test
  script:
    - chmod +x ./gradlew
    - ./gradlew check

