image: gradle:jdk11

stages:
  - build
  - tests

before_script:
  - export GRADLE_USER_HOME='pwd'/.gradle

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .gradle/wrapper
    - .gradle/caches

package:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew assemble

test:
  stage: tests
  script:
    - chmod +x ./gradlew
    - ./gradlew check

